from elasticsearch import Elasticsearch
from datetime import datetime
# Password for the 'elastic' user generated by Elasticsearch

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="/Users/vamsi/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())



def index_a_document(es):
    doc = {
    'author': 'jk rowling',
    'text': 'Interesting content...',
    'timestamp': datetime.now(),
    }
    resp = es.index(index="test-index", id=1, document=doc)
    print(resp['result'])


def get_a_document(es):
    print("inside get document")
    resp = es.get(index="test-index", id=1)
    print(resp['_source'])


def search_for_document(es):
    print("inside search for documents")
    resp = es.search(index="test-index", query={"match_all": {}})
    print("Got %d Hits:" % resp['hits']['total']['value'])
    for hit in resp['hits']['hits']:
        print("%(timestamp)s %(author)s: %(text)s" % hit["_source"])


if(__name__=="__main__"):
    index_a_document(client)
    get_a_document(client)
    search_for_document(client)